# Generated by Django 2.0.13 on 2019-05-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190519_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
